server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
            
  jpa:
    open-in-view: true
    hibernate:
      #create - 서버 시작시마다 DB초기화
      #update - 수정사항만 DB에 반영
      #none - DB에 아무런 반영을 하지 않음.
      ddl-auto: update # create: 서버가 실행 될때마다 DB 테이블을 지우고 다시 만듬.(처음서버 실행 후 테이블 생성되면 ''update' 로 변경해야됨)
      # org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl : 엔티티를 만들 때 변수명 그대로 DB에 필드를 만들어 준다. (예: java: createDate  -> DB: createDate )
      # org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy : 엔티티를 만들 때 변수명에 언더스코어를 붙여준다. 생성(예: java: createDate  -> DB: create_date)  
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #jpa에서 사용하는 넘버링 사용안함
    show-sql: true # 콘솔창에 쿼리 조회시켜줌
    properties:
      hibernate.format_sql: true # 콘솔창 퀴리 정렬 시킴

  jackson:
    serialization:
      fail-on-empty-beans: false
      